spring:
  application:
    name: adminserver
  zipkin:
    base-url: http://192.168.50.49:9411
server:
  port: 8889
eureka:
  instance:
    ip-address: 192.168.50.49
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://192.168.50.49:8080/eureka/
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        # 注意：此处在视频里是 include: ["health", "info"] 但已无效了，请修改
        include: health,info
