
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8801/eureka/
server:
  port: 8885
spring:
  application:
    name: feign-consumer
  zipkin:
    base-url: http://localhost:9411
feign:
  hystrix:
    enabled: true