
server:
  port: 8881
spring:
  application:
    name: service-hi

eureka:
  instance:
    ip-address: 192.168.50.45
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://192.168.50.45:8080/eureka/