profiles: dev
spring:
  profiles:
    active: dev
  application:
    name: service-hi
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8889
  # 配置数据库信息
  datasource:
    # 数据源配置
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/mp?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: org.postgresql.Driver
    # 初始化 最小 最大
    initial-size: 5
    min-idle: 5
    max-active: 20
    # 配置获取连接等待超时的时间
    max-wait: 60000
eureka:
  #  instance:
  #    ip-address: 192.168.50.49
  #    prefer-ip-address: true
  #    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8881
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"