server:
  port: 8886
eureka:
  instance:
    ip-address: 192.168.50.49
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://192.168.50.49:8080/eureka/,http://192.168.50.49:8081/eureka/

spring:
  application:
    name: zuulserver
  zipkin:
    base-url: http://${eureka.instance.ip-address}:9411
  boot:
    admin:
      client:
        url: http://${eureka.instance.ip-address}:8889
  # 消息总线相关配置
  rabbitmq:
    host: 192.168.50.49
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
    trace: 
      enabled: true # 开启消息跟踪            
zuul:
  routes:
    oauth2-server:
      path: /zegooauth/**
      serviceId: oauth2-server
      sensitiveHeaders: "*"
    storage-baseinfo:
      path: /baseinfo/**
      serviceId: storage-baseinfo
      sensitiveHeaders: "*"
    storage-product:
      path: /product/**
      serviceId: storage-product
      sensitiveHeaders: "*"
  retryable: false
  ignored-services: "*"
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000


# spring security oauth2
security:
  oauth2:
    client:
      access-token-uri: http://localhost:${server.port}/zegooauth/oauth/token
      user-authorization-uri: http://localhost:${server.port}/zegooauth/oauth/authorize
      client-id: clientid
    resource:
      user-info-uri:  http://localhost:${server.port}/zegooauth/api/member
      prefer-token-info: false
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

hystrix:
  command:
    default:
      execution:
        timeout: #配置命令的执行，是否会超时
          enabled: true
        isolation: #命令的执行超时时间  超时将执行回退
          thread:
            timeoutInMilliseconds: 20000


ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000