server:
  port: 8886

spring:
  application:
    name: zuulserver
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-hi
    api-b:
      path: /api-b/**
      serviceId:  feign-consumer