server:
  port: 8886

spring:
  application:
    name: zuulserver
eureka:
  instance:
    ip-address: 192.168.50.49
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://192.168.50.49:8080/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-hi
    api-b:
      path: /api-b/**
      serviceId:  feign-consumer