server:
  port: 8886
eureka:
  instance:
    ip-address: 192.168.50.49
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://192.168.50.49:8080/eureka/,http://192.168.50.49:8081/eureka/

spring:
  application:
    name: zuulserver
  zipkin:
    base-url: http://${eureka.instance.ip-address}:9411
  boot:
    admin:
      client:
        url: http://${eureka.instance.ip-address}:8889
  # 消息总线相关配置
  rabbitmq:
    host: 192.168.50.49
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
    trace: 
      enabled: true # 开启消息跟踪            
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-hi
    api-b:
      path: /api-b/**
      serviceId:  feign-consumer
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"